# for getting the dates of each lecture
class_num: '10-718'
dates_without_class:
 - month: 1
   date: 19
 - month: 3
   date: 3
 - month: 3
   date: 5
 - month: 4
   date: 9
start_date: 
   month: 1
   date: 12
end_date: 
   month: 4
   date: 24
lecture_days: [1, 3]  # Mon = 1
year: 2026
